# Generated by Django 5.2.5 on 2025-08-10 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='source_topic',
            new_name='topic',
        ),
    ]
