# Generated by Django 5.2.5 on 2025-08-13 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_source_topic_question_topic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='accuracy',
            field=models.FloatField(default=-1.0),
        ),
        migrations.AddField(
            model_name='topic',
            name='accuracy_last_updated',
            field=models.DateTimeField(auto_now_add=True, default='2025-08-13 18:08:30.123456'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='total_questions_answered',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RevisionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('last_generated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revision_note', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
