# Generated by Django 5.2.5 on 2025-08-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_topic_accuracy_topic_accuracy_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='correct_answers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='wrong_answers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
