# Generated by Django 5.2.5 on 2025-08-13 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_topic_correct_answers_topic_wrong_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='total_questions_answered',
        ),
    ]
